version: "3.9"

volumes:
  postgres_volume:

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
  bot:
    build: bot/
    environment:
      - TOKEN=${TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    restart: always